import oracledb
import os

dsn = os.getenv("ORA_DSN", "localhost/xepdb1")

connection = oracledb.connect(
    user=os.getenv("ORA_USER", "system"),
    password=os.getenv("ORA_PASS", "admin"),
    dsn=dsn,
)
cursor = connection.cursor()

cursor.execute(
    """
BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE FACE_DETECTIONS (
        ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
        UUID VARCHAR2(36) UNIQUE,
        UPLOADED_IMAGE_ID VARCHAR2(36) NOT NULL,
        DETECTED_HUMAN_ID VARCHAR2(36) NOT NULL,
        SOURCE_PHOTO_ID VARCHAR2(36) NOT NULL,
        DETECTED_BBOX CLOB,
        CONFIDENCE NUMBER(5,4) NOT NULL,
        EMOTION_CODE VARCHAR2(50),
        CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
        CONSTRAINT FACE_DETECTIONS_UPLOADED_FK FOREIGN KEY (UPLOADED_IMAGE_ID) REFERENCES UPLOADED_IMAGES(UUID) ON DELETE CASCADE,
        CONSTRAINT FACE_DETECTIONS_HUMAN_FK FOREIGN KEY (DETECTED_HUMAN_ID) REFERENCES HUMANS(UUID) ON DELETE CASCADE,
        CONSTRAINT FACE_DETECTIONS_SOURCE_PHOTO_FK FOREIGN KEY (SOURCE_PHOTO_ID) REFERENCES USER_PHOTOS(UUID) ON DELETE CASCADE
    )';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;"""
)

connection.commit()

cursor.execute(
    """
BEGIN
    EXECUTE IMMEDIATE 'CREATE INDEX FACE_DETECTIONS_UPLOADED_IDX ON FACE_DETECTIONS(UPLOADED_IMAGE_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX FACE_DETECTIONS_HUMAN_IDX ON FACE_DETECTIONS(DETECTED_HUMAN_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX FACE_DETECTIONS_SOURCE_PHOTO_IDX ON FACE_DETECTIONS(SOURCE_PHOTO_ID)';
    EXECUTE IMMEDIATE 'CREATE INDEX FACE_DETECTIONS_CONFIDENCE_IDX ON FACE_DETECTIONS(CONFIDENCE)';
    EXECUTE IMMEDIATE 'CREATE INDEX FACE_DETECTIONS_EMOTION_IDX ON FACE_DETECTIONS(EMOTION_CODE)';
    EXECUTE IMMEDIATE 'CREATE INDEX FACE_DETECTIONS_CREATED_IDX ON FACE_DETECTIONS(CREATED_AT)';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -955 THEN
            RAISE;
        END IF;
END;"""
)

connection.commit()
cursor.close()
connection.close()
